### ISSUE TITLE
org.httpkit.client/request without callback throws clojure.lang.ArityException

### ISSUE THREAD

**Issue by jruusu** [Yleisradio/http-kit-newrelic#2]
With this hook enabled, direct invocation of `org.httpkit.client/request` with just one argument (opts map):
```clojure
(org.httpkit.client/request {:method :get :url "http://example.org"})
```
fails with `clojure.lang.ArityException: Wrong number of args (2) passed to: http-kit-newrelic.core/request-hook`

**Comment by paulibyckling** [comment]
Suljetaan vanhentuneena.
